/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ResetPasswordRequest {
  confirmPassword?: string;
  newPassword?: string;
  token?: string;
}
